# Generated by Django 4.0.3 on 2023-12-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_product_key', models.CharField(max_length=50)),
                ('license_expiration_date', models.DateTimeField(null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=255)),
                ('windows_version', models.CharField(max_length=50)),
            ],
        ),
    ]
