# Generated by Django 4.0.3 on 2023-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_installedapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installedapplication',
            old_name='install_date',
            new_name='installed_on',
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='publisher',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
