# Generated by Django 4.0.3 on 2023-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_install_date_installedapplication_installed_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
        migrations.DeleteModel(
            name='InstalledApplication',
        ),
    ]
