# Generated by Django 4.0.3 on 2023-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_installedapp_delete_installedapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapp',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
