# Generated by Django 4.0.3 on 2023-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_installedapp_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mac_id', models.CharField(max_length=17)),
                ('ip_address', models.CharField(max_length=15)),
                ('linux_distribution', models.CharField(max_length=255)),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('sent_mb', models.FloatField()),
                ('received_mb', models.FloatField()),
                ('host_name', models.CharField(max_length=255)),
            ],
        ),
    ]
