# Generated by Django 4.0.3 on 2023-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_monitoringdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringdata',
            name='mac_id',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
