# Generated by Django 4.0.3 on 2023-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_monitoringdata_mac_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_address', models.GenericIPAddressField()),
                ('router_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('poll_using', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
