# Generated by Django 4.0.3 on 2023-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='port',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
