# Generated by Django 4.0.3 on 2023-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_router_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='Name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
