# Generated by Django 4.0.3 on 2023-12-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_router_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('response_time', models.FloatField()),
                ('http_status_code', models.PositiveIntegerField()),
                ('http_method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('user_agent', models.TextField()),
                ('elb_arn', models.CharField(max_length=255)),
                ('backend_status_code', models.PositiveIntegerField()),
                ('backend_ip_port', models.CharField(max_length=20)),
            ],
        ),
    ]
